repos:
  - repo: local
    hooks:
      - id: tidy-html5
        name: tidy-html5
        entry: tidy -m -quiet -indent -wrap 100 -utf8 --new-blocklevel-tags "rs-module-wrap rs-module rs-slides rs-slide rs-layer"
        language: system
        files: \.html$
        pass_filenames: true
