repos:
  - repo: https://github.com/djlint/djlint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-jinja
        files: ^templates/.*\.html$
        types_or: ["html"]
        args: ["--indent", "2"]
