[build]
  publish = "public"

[[edge_functions]]
  path = "/donate"
  function = "donate"

[[edge_functions]]
  path = "/donate-qr"
  function = "donate"

[[edge_functions]]
  path = "/support-us"
  function = "donate"

[[redirects]]
  from = "https://ukuleletuesday.ie/*"
  to = "https://www.ukuleletuesday.ie/:splat"
  status = 301
  force = true
  headers = { Cache-Control = "public, max-age=31536000" }

# --- Headers ---
# HTML: short cache, revalidate in background
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=60, stale-while-revalidate=86400"

# CSS/JS: short cache to allow updates (5 minutes + stale-while-revalidate)
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=300, stale-while-revalidate=86400"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=300, stale-while-revalidate=86400"

# Static assets: moderate cache to avoid stale artifacts
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"

# Edge function endpoints: no caching
[[headers]]
  for = "/donate"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/donate-qr"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/support-us"
  [headers.values]
    Cache-Control = "no-store"
