[build]
  publish = "public"

[[edge_functions]]
  path = "/donate"
  function = "donate"

[[edge_functions]]
  path = "/donate-qr"
  function = "donate"

[[edge_functions]]
  path = "/support-us"
  function = "donate"