name: Export Static Site

on:
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on schedule (daily at 2 AM UTC)
  schedule:
    - cron: '0 2 * * *'
  
  # Run on pushes to main branch (for testing)
  push:
    branches: [ main ]

jobs:
  export-and-deploy:
    runs-on: ubuntu-latest
    
    # Grant GITHUB_TOKEN write permissions for Pages deployment
    permissions:
      contents: read
      pages: write
      id-token: write
    
    # Use a concurrency group to prevent multiple exports running simultaneously
    concurrency:
      group: "pages"
      cancel-in-progress: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl
    
    - name: Make script executable
      run: chmod +x ./run-static-export.sh
    
    - name: Run static export
      env:
        WP_USERNAME: ${{ secrets.WP_USERNAME }}
        WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
      run: ./run-static-export.sh
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './static-export'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
