name: Export Static Site

on:
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on schedule (daily at 2 AM UTC)
  schedule:
    - cron: '0 2 * * *'
  
  # Run on pushes to main branch (for testing)
  push:
    branches: [ main ]

jobs:
  export-and-deploy:
    runs-on: ubuntu-latest
    
    # Use a concurrency group to prevent multiple exports running simultaneously
    concurrency:
      group: "netlify-deploy"
      cancel-in-progress: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    
    - name: Run static export
      env:
        WP_USERNAME: ${{ secrets.WP_USERNAME }}
        WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
      run: uv run export.py download -o ./static-export
    
    - name: Fix paths in static site
      run: |
        cd ./static-export
        grep -rl --include='*.html' 'action=dynamic_css#038;ver=6.8.1' . \
          | xargs sed -i \
              's@/wp-admin/admin-ajax\.php?action=dynamic_css#038;ver=6\.8\.1@/wp-admin/admin-ajax.css@g'
        echo "✓ Fixed paths in static site"
    
    - name: Copy extra assets
      run: |
        if [ -d "./extra-assets" ]; then
          cp -r ./extra-assets/* ./static-export/
          echo "✓ Copied extra assets to static-export"
        else
          echo "No extra-assets directory found, skipping"
        fi
    
    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=./static-export --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
